mention support for plugins requires object configuration {} (#240)
* Add not correct way to add plugins

I think this PR could save others who has the issue of Cannot query field "code" on type "Node".

```
  Error: Cannot query field "code" on type "Node". Did you mean to use an inline fragment on "Mdx"?                                                                                                                
  GraphQL request (13:15)                                                                                                                                                                                          
  12:               }                                                                                                                                                                                              
  13:               code {                                                                                                                                                                                         
                    ^                                                                                                                                                                                              
  14:                 scope

```